# IBM MQ Configuration
ibm.mq.queue-manager=QM1
# Your Queue Manager
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.conn-name=localhost(1414)
#ibm.mq.user=your-username            # Optional - MQ username
#ibm.mq.password=your-password        # Optional - MQ password
ibm.mq.queue=DEV.QUEUE.1